name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Build
        env:
          REACT_APP_API_TOKEN: ${{ secrets.REACT_APP_API_TOKEN }}
          REACT_APP_PUBLIC_URL: ${{secrets.REACT_APP_PUBLIC_URL}}
          REACT_APP_TMBD_URL: ${{secrets.REACT_APP_TMBD_URL}}
          REACT_APP_IMAGE_URL: ${{secrets.REACT_APP_IMAGE_URL}}
          REACT_APP_POSTER_IMAGE: ${{secrets.REACT_APP_POSTER_IMAGE}}
          REACT_APP_BACKDROP_IMAGE: ${{secrets.REACT_APP_BACKDROP_IMAGE}}
        run: yarn build

      - name: Deploy to Production
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './build'
          production-branch: master
          production-deploy: true
          deploy-message: 'Production Deploy'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
